package com.ntg.core.designsystem.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF50A8EB)
val OnPrimaryLight = Color(0xFFDCEDFB)
val PrimaryContainerLight = Color(0xFFDCEDFB)
val OnPrimaryContainerLight = Color(0xFF50A8EB)
val SecondaryLight = Color(0xFF14CC8F)
val OnSecondaryLight = Color(0xFFE8FAF4)
val SecondaryContainerLight = Color(0xFFE8FAF4)
val OnSecondaryContainerLight = Color(0xFF14CC8F)
val TertiaryLight = Color(0xFFFFC107)
val OnTertiaryLight = Color(0xFFFFEAB8)
val TertiaryContainerLight = Color(0xFFFFEAB8)
val OnTertiaryContainerLight = Color(0xFFFFC107)
val ErrorLight = Color(0xFFFE3E3E)
val OnErrorLight = Color(0xFFFFECEC)
val ErrorContainerLight = Color(0xFFFFECEC)
val OnErrorContainerLight = Color(0xFFFE3E3E)
val SurfaceLight = Color(0xFFF7F9FF)
val SurfaceDimLight = Color(0xFFD7DADF)
val SurfaceBrightLight = Color(0xFFF7F9FF)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF1F4F9)
val SurfaceContainerLight = Color(0xFFEBEEF3)
val SurfaceContainerHighLight = Color(0xFFE6E8EE)
val SurfaceContainerHighestLight = Color(0xFFE0E2E8)
val OnSurfaceLight = Color(0xFF000000)
val OnSurfaceVarLight = Color(0xFF1F242A)
val OutlineLight = Color(0xFF626972)
val OutlineVarientLight = Color(0xFF3E434A)
val InverseSurfaceLight = Color(0xFF2D3135)
val InverseOnSurfaceLight = Color(0xFFFFFFFF)
val InversePrimaryLight = Color(0xFFDFEEFF)
val ShadowLight = Color(0xFF000000)
val ScrimLight = Color(0xFF000000)









val PrimaryDark = Color(0xFF50A8EB)
val OnPrimaryDark = Color(0xFFDCEDFB)
val PrimaryContainerDark = Color(0xFFB9DCF7)
val OnPrimaryContainerDark = Color(0xFF4086BC)
val SecondaryDark = Color(0xFF14CC8F)
val OnSecondaryDark = Color(0xFFE8FAF4)
val SecondaryContainerDark = Color(0xFFC4F2E3)
val OnSecondaryContainerDark = Color(0xFF0F9573)
val TertiaryDark = Color(0xFFFFC107)
val OnTertiaryDark = Color(0xFFFFEAB8)
val TertiaryContainerDark = Color(0xFFFFDF95)
val OnTertiaryContainerDark = Color(0xFFD09E14)
val ErrorDark = Color(0xFFFE3E3E)
val OnErrorDark = Color(0xFFFFECEC)
val ErrorContainerDark = Color(0xFFFFD8D8)
val OnErrorContainerDark = Color(0xFFCB3232)
val SurfaceDark = Color(0xFF101418)
val SurfaceDimDark = Color(0xFF262727)
val SurfaceBrightDark = Color(0xFF36393E)
val SurfaceContainerLowestDark = Color(0xFF0B0F12)
val SurfaceContainerLowDark = Color(0xFF181C20)
val SurfaceContainerDark = Color(0xFF1C2024)
val SurfaceContainerHighDark = Color(0xFF272A2E)
val SurfaceContainerHighestDark = Color(0xFF313539)
val OnSurfaceDark = Color(0xFFFFFFFF)
val OnSurfaceVarDark = Color(0xFFF9FAFF)
val OutlineDark = Color(0xFFB0B5BD)
val OutlineVarientDark = Color(0xFFC6CBD3)
val InverseSurfaceDark = Color(0xFFE0E2E8)
val InverseOnSurfaceDark = Color(0xFF000000)
val InversePrimaryDark = Color(0xFF002D48)
val ShadowDark = Color(0xFF000000)
val ScrimDark = Color(0xFF000000)